package com.example.loravisualizer;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.*;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;

public class VisualizerApplication extends Application {
    @Override
    public void start(Stage stage) throws IOException {

//        System.setProperty("prism.order", "es2");

        BorderPane root = new BorderPane();
        root.setTop(MenuBarManager.createMenuBar());



        MenuBarManager.addMenuBarListener(new MenuBarManager.MenuBarListener() {
            @Override
            public void onFileLoadItemClicked() {
                openFileChooser(stage);
            }

            @Override
            public void onExitItemClicked() {
                System.exit(0);
            }

            @Override
            public void onLiveLogItemClicked(boolean isSelected) {
                if(isSelected)
                    LiveLogBox.getLogBox().show();
                else
                    LiveLogBox.getLogBox().hide();
            }
        });



        Scene scene = new Scene(root);

        VBox vbox = new VBox();
        vbox.setPadding(new Insets(63));
        vbox.setSpacing(9);
        vbox.setAlignment(Pos.CENTER);

        Label label = new Label("Welcome to Lora Visualizer!");
        label.setFont(Font.font(Font.getDefault().getFamily(), FontWeight.BOLD, FontPosture.REGULAR,15));
        vbox.getChildren().add(label);

        Label label2 = new Label("Click to load the simulation file generated by the Lorawan module");
        label2.setFont(Font.font(Font.getDefault().getFamily(), FontWeight.NORMAL, FontPosture.REGULAR,12));
        vbox.getChildren().add(label2);

        Button button = new Button();
        button.setText("Load");
        button.setOnAction(event -> openFileChooser(stage));

        vbox.getChildren().add(button);


        root.setCenter(vbox);


        stage.setOnCloseRequest(event -> {
            System.exit(0);
        });

        stage.setTitle("Lora Visualizer");
        stage.setScene(scene);
        stage.show();
    }

    public void openFileChooser(Stage primaryStage){
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select a File");

        File selectedFile = fileChooser.showOpenDialog(primaryStage);

        if (selectedFile != null) {

            LoraAnimationParser loraAnimationParser = new LoraAnimationParser(selectedFile);
            primaryStage.setScene(
                    new LoraAnimator(
                            loraAnimationParser.getNodes(),
                            loraAnimationParser.getHighestX(),
                            loraAnimationParser.getHighestY(),
                            loraAnimationParser.getLoraTimeline()
                    )
            );

        } else {
            System.out.println("No file selected.");
        }
    }

    public static void main(String[] args) {
        launch();
    }
}